---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: robkaandorp/edstarmapvisualizer
    auto_tag: true
    dry_run: true
    purge: false

trigger:
  branch:
  - master