---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:10-alpine
  commands:
  - apt-get update -qq
  - apt-get install -y -qq libzmq-dev
  - npm install
  - webpack

trigger:
  branch:
  - master