---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:10-alpine
  commands:
  - apk add --update make gcc g++ python zeromq zeromq-dev
  - npm install
  - webpack

trigger:
  branch:
  - master